### ISSUE TITLE
Stuff that still doesn't work

### ISSUE THREAD

**Issue by hubbardip** [vtao21/physics-playground#3]
1. Each pixel is treated as a meter, which doesn't give a great sense of scale.
2. The way it's currently implemented (with dx, dy, and whatnot), the ball doesn't stop if it moves offscreen.
3. No user input yet (I'm currently working on this, since it's certainly something we need).

**Comment by hubbardip** [comment]
(2) is now solved.

**Comment by hubbardip** [comment]
(1) is solved

**Comment by v-tao** [comment]
don't (1) is solved me. literally that is so boring. (1) is solved literally did your English teachers never teach you to use active voice??? smh my head yw Isaac for making the meters into pixels >:( i hope your next cottage cheese is as dry as the sahara desert, nay, even drier.
